version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs
    ports:
      - '3001:3001'
      - '8001:8001'
    working_dir: /usr/src
    volumes:
      - .:/usr/src
    env_file:
      - .env
    depends_on:
      - rabbitmq
